// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0

import { Writer, Reader } from "as-proto/assembly";
import { Timestamp } from "../../google/protobuf/Timestamp";

export class groupp_EarningsWithdrawn {
  static encode(message: groupp_EarningsWithdrawn, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.evtTxHash);

    writer.uint32(16);
    writer.uint32(message.evtIndex);

    const evtBlockTime = message.evtBlockTime;
    if (evtBlockTime !== null) {
      writer.uint32(26);
      writer.fork();
      Timestamp.encode(evtBlockTime, writer);
      writer.ldelim();
    }

    writer.uint32(32);
    writer.uint64(message.evtBlockNumber);

    writer.uint32(42);
    writer.string(message.evtAddress);

    writer.uint32(50);
    writer.bytes(message.lender);

    writer.uint32(58);
    writer.string(message.amountPoolSharesTokens);

    writer.uint32(66);
    writer.string(message.principalTokensWithdrawn);

    writer.uint32(74);
    writer.bytes(message.recipient);
  }

  static decode(reader: Reader, length: i32): groupp_EarningsWithdrawn {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new groupp_EarningsWithdrawn();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.evtTxHash = reader.string();
          break;

        case 2:
          message.evtIndex = reader.uint32();
          break;

        case 3:
          message.evtBlockTime = Timestamp.decode(reader, reader.uint32());
          break;

        case 4:
          message.evtBlockNumber = reader.uint64();
          break;

        case 5:
          message.evtAddress = reader.string();
          break;

        case 6:
          message.lender = reader.bytes();
          break;

        case 7:
          message.amountPoolSharesTokens = reader.string();
          break;

        case 8:
          message.principalTokensWithdrawn = reader.string();
          break;

        case 9:
          message.recipient = reader.bytes();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  evtTxHash: string;
  evtIndex: u32;
  evtBlockTime: Timestamp | null;
  evtBlockNumber: u64;
  evtAddress: string;
  lender: Uint8Array;
  amountPoolSharesTokens: string;
  principalTokensWithdrawn: string;
  recipient: Uint8Array;

  constructor(
    evtTxHash: string = "",
    evtIndex: u32 = 0,
    evtBlockTime: Timestamp | null = null,
    evtBlockNumber: u64 = 0,
    evtAddress: string = "",
    lender: Uint8Array = new Uint8Array(0),
    amountPoolSharesTokens: string = "",
    principalTokensWithdrawn: string = "",
    recipient: Uint8Array = new Uint8Array(0)
  ) {
    this.evtTxHash = evtTxHash;
    this.evtIndex = evtIndex;
    this.evtBlockTime = evtBlockTime;
    this.evtBlockNumber = evtBlockNumber;
    this.evtAddress = evtAddress;
    this.lender = lender;
    this.amountPoolSharesTokens = amountPoolSharesTokens;
    this.principalTokensWithdrawn = principalTokensWithdrawn;
    this.recipient = recipient;
  }
}
