// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0

import { Writer, Reader } from "as-proto/assembly";
import { Timestamp } from "../../google/protobuf/Timestamp";

export class groupp_LoanRepaid {
  static encode(message: groupp_LoanRepaid, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.evtTxHash);

    writer.uint32(16);
    writer.uint32(message.evtIndex);

    const evtBlockTime = message.evtBlockTime;
    if (evtBlockTime !== null) {
      writer.uint32(26);
      writer.fork();
      Timestamp.encode(evtBlockTime, writer);
      writer.ldelim();
    }

    writer.uint32(32);
    writer.uint64(message.evtBlockNumber);

    writer.uint32(42);
    writer.string(message.evtAddress);

    writer.uint32(50);
    writer.string(message.bidId);

    writer.uint32(58);
    writer.bytes(message.repayer);

    writer.uint32(66);
    writer.string(message.principalAmount);

    writer.uint32(74);
    writer.string(message.interestAmount);

    writer.uint32(82);
    writer.string(message.totalPrincipalRepaid);

    writer.uint32(90);
    writer.string(message.totalInterestCollected);
  }

  static decode(reader: Reader, length: i32): groupp_LoanRepaid {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new groupp_LoanRepaid();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.evtTxHash = reader.string();
          break;

        case 2:
          message.evtIndex = reader.uint32();
          break;

        case 3:
          message.evtBlockTime = Timestamp.decode(reader, reader.uint32());
          break;

        case 4:
          message.evtBlockNumber = reader.uint64();
          break;

        case 5:
          message.evtAddress = reader.string();
          break;

        case 6:
          message.bidId = reader.string();
          break;

        case 7:
          message.repayer = reader.bytes();
          break;

        case 8:
          message.principalAmount = reader.string();
          break;

        case 9:
          message.interestAmount = reader.string();
          break;

        case 10:
          message.totalPrincipalRepaid = reader.string();
          break;

        case 11:
          message.totalInterestCollected = reader.string();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  evtTxHash: string;
  evtIndex: u32;
  evtBlockTime: Timestamp | null;
  evtBlockNumber: u64;
  evtAddress: string;
  bidId: string;
  repayer: Uint8Array;
  principalAmount: string;
  interestAmount: string;
  totalPrincipalRepaid: string;
  totalInterestCollected: string;

  constructor(
    evtTxHash: string = "",
    evtIndex: u32 = 0,
    evtBlockTime: Timestamp | null = null,
    evtBlockNumber: u64 = 0,
    evtAddress: string = "",
    bidId: string = "",
    repayer: Uint8Array = new Uint8Array(0),
    principalAmount: string = "",
    interestAmount: string = "",
    totalPrincipalRepaid: string = "",
    totalInterestCollected: string = ""
  ) {
    this.evtTxHash = evtTxHash;
    this.evtIndex = evtIndex;
    this.evtBlockTime = evtBlockTime;
    this.evtBlockNumber = evtBlockNumber;
    this.evtAddress = evtAddress;
    this.bidId = bidId;
    this.repayer = repayer;
    this.principalAmount = principalAmount;
    this.interestAmount = interestAmount;
    this.totalPrincipalRepaid = totalPrincipalRepaid;
    this.totalInterestCollected = totalInterestCollected;
  }
}
