schema: schema.introspection.graphql
extensions:
  endpoints:
    Mainnet:
      url: https://api.studio.thegraph.com/query/36377/tellerv2-mainnet/version/latest
      headers:
        user-agent: JS GraphQL
      introspect: true
    Polygon:
      url: https://api.studio.thegraph.com/query/36377/tellerv2-polygon/version/latest
      headers:
        user-agent: JS GraphQL
      introspect: true
    Arbitrum:
      url: https://api.studio.thegraph.com/query/36377/tellerv2-arbitrum/version/latest
      headers:
        user-agent: JS GraphQL
      introspect: true
    Goerli:
      url: https://api.studio.thegraph.com/query/36377/tellerv2-goerli/version/latest
      headers:
        user-agent: JS GraphQL
      introspect: true
    Local GraphQL Endpoint:
      url: http://localhost:8080/graphql
      headers:
        user-agent: JS GraphQL
      introspect: true
