overrides:
  - files:
      - "contracts/**/*.sol"
      - "tests/**/*.sol"
    options:
      explicitTypes: "always"
      printWidth: 80
      tabWidth: 4
      useTabs: false
      singleQuote: false
      bracketSpacing: true
      arrowParens: "always"
      semi: true
  - files: "*.ts"
    options:
      printWidth: 80
      tabWidth: 2
      useTabs: false
      singleQuote: true
      bracketSpacing: true
      arrowParens: "always"
      semi: false
