[profile.default]
src = 'contracts'
out = 'generated/artifacts_forge'
libs = ['node_modules', 'lib']
test = 'tests'
cache_path  = 'generated/cache_forge'
remappings = [
    "uniswap-v3-periphery/=lib/v3-periphery-foundry/",
]
fs_permissions = [
    { access = "read", path = "./"},
    { access = "read", path = "./lib"}
]

[rpc_endpoints]
mainnet = "https://eth-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}"

[doc]
homepage= "HOME.md"
ignore = [
    "*/EAS/*.sol",
    "*/mock/*.sol",

    "*/TellerV0Storage.sol",
    "*/ProtocolFeeMock.sol",
    "*/TellerV2Mock.sol",

    "*/libraries/*.*",
    "*/types/*.*",
    "*/Types/*.*",
    "*/interfaces/*.*",
    "*/interfaces/escrow/*.*", 
    "*/README.md",
]